# Deploy local file to the dev environment
name: "Deploy Environment Test"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - dev
          - prod
  push:
    branches:
      - master

jobs:
  deploy-env:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to ${{ github.event.inputs.environment }}
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }}"
          echo "Using the following environment variables:"
          ## This will use the BUCKET_NAME var from the Environment
          echo "  - ENVIRONMENT: ${{ vars.BUCKET_NAME }}"
      - name: Dump the var object
        run: |
          echo "Dumping the vars object"
          echo "${{ toJson(vars) }}"
